# coding: utf-8

"""
    PriceList Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pricelist.models.pricelist_currency import PricelistCurrency
from pricelist.models.pricelist_get_full_price_item_price import PricelistGetFullPriceItemPrice
from pricelist.models.pricelist_money import PricelistMoney
from typing import Optional, Set
from typing_extensions import Self

class PricelistGetFullPriceItem(BaseModel):
    """
    PricelistGetFullPriceItem
    """ # noqa: E501
    id: Optional[StrictStr] = None
    grn: Optional[StrictStr] = None
    item_grn: Optional[StrictStr] = Field(default=None, alias="itemGrn")
    base_price: Optional[PricelistMoney] = Field(default=None, alias="basePrice")
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    currency: Optional[PricelistCurrency] = PricelistCurrency.XXX
    prices: Optional[List[PricelistGetFullPriceItemPrice]] = None
    has_tier_prices: Optional[StrictBool] = Field(default=None, alias="hasTierPrices")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["id", "grn", "itemGrn", "basePrice", "createdAt", "updatedAt", "currency", "prices", "hasTierPrices"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PricelistGetFullPriceItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of base_price
        if self.base_price:
            _dict['basePrice'] = self.base_price.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in prices (list)
        _items = []
        if self.prices:
            for _item_prices in self.prices:
                if _item_prices:
                    _items.append(_item_prices.to_dict())
            _dict['prices'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PricelistGetFullPriceItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "grn": obj.get("grn"),
            "itemGrn": obj.get("itemGrn"),
            "basePrice": PricelistMoney.from_dict(obj["basePrice"]) if obj.get("basePrice") is not None else None,
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "currency": obj.get("currency") if obj.get("currency") is not None else PricelistCurrency.XXX,
            "prices": [PricelistGetFullPriceItemPrice.from_dict(_item) for _item in obj["prices"]] if obj.get("prices") is not None else None,
            "hasTierPrices": obj.get("hasTierPrices")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


