# coding: utf-8

"""
    PriceList Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from pricelist.models.pricelist_money import PricelistMoney
from pricelist.models.pricelist_set_price_list_item_price import PricelistSetPriceListItemPrice
from typing import Optional, Set
from typing_extensions import Self

class PricelistSetPriceListItem(BaseModel):
    """
    PricelistSetPriceListItem
    """ # noqa: E501
    item_grn: Optional[StrictStr] = Field(default=None, alias="itemGrn")
    base_price: Optional[PricelistMoney] = Field(default=None, alias="basePrice")
    price_items: Optional[List[PricelistSetPriceListItemPrice]] = Field(default=None, alias="priceItems")
    has_tier_prices: Optional[StrictBool] = Field(default=None, alias="hasTierPrices")
    additional_properties: Dict[str, Any] = {}
    __properties: ClassVar[List[str]] = ["itemGrn", "basePrice", "priceItems", "hasTierPrices"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of PricelistSetPriceListItem from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * Fields in `self.additional_properties` are added to the output dict.
        """
        excluded_fields: Set[str] = set([
            "additional_properties",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of base_price
        if self.base_price:
            _dict['basePrice'] = self.base_price.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in price_items (list)
        _items = []
        if self.price_items:
            for _item_price_items in self.price_items:
                if _item_price_items:
                    _items.append(_item_price_items.to_dict())
            _dict['priceItems'] = _items
        # puts key-value pairs in additional_properties in the top level
        if self.additional_properties is not None:
            for _key, _value in self.additional_properties.items():
                _dict[_key] = _value

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of PricelistSetPriceListItem from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "itemGrn": obj.get("itemGrn"),
            "basePrice": PricelistMoney.from_dict(obj["basePrice"]) if obj.get("basePrice") is not None else None,
            "priceItems": [PricelistSetPriceListItemPrice.from_dict(_item) for _item in obj["priceItems"]] if obj.get("priceItems") is not None else None,
            "hasTierPrices": obj.get("hasTierPrices")
        })
        # store additional fields in additional_properties
        for _key in obj.keys():
            if _key not in cls.__properties:
                _obj.additional_properties[_key] = obj.get(_key)

        return _obj


