# coding: utf-8

"""
    PriceList Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pricelist.models.pricelist_price_list_type import PricelistPriceListType

class TestPricelistPriceListType(unittest.TestCase):
    """PricelistPriceListType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPricelistPriceListType(self):
        """Test PricelistPriceListType"""
        # inst = PricelistPriceListType()

if __name__ == '__main__':
    unittest.main()
