# coding: utf-8

"""
    PriceList Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pricelist.models.pricelist_list_full_price_items_request import PricelistListFullPriceItemsRequest

class TestPricelistListFullPriceItemsRequest(unittest.TestCase):
    """PricelistListFullPriceItemsRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PricelistListFullPriceItemsRequest:
        """Test PricelistListFullPriceItemsRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PricelistListFullPriceItemsRequest`
        """
        model = PricelistListFullPriceItemsRequest()
        if include_optional:
            return PricelistListFullPriceItemsRequest(
                tenant_id = '',
                id = '',
                page_size = 56,
                page_token = ''
            )
        else:
            return PricelistListFullPriceItemsRequest(
        )
        """

    def testPricelistListFullPriceItemsRequest(self):
        """Test PricelistListFullPriceItemsRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
