# coding: utf-8

"""
    PriceList Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pricelist.api.price_list_api import PriceListApi


class TestPriceListApi(unittest.TestCase):
    """PriceListApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PriceListApi()

    def tearDown(self) -> None:
        pass

    def test_create_price_list(self) -> None:
        """Test case for create_price_list

        Create new list
        """
        pass

    def test_delete_price_list_items(self) -> None:
        """Test case for delete_price_list_items

        Get prices for items
        """
        pass

    def test_get_full_price_items_by_pricelist_id(self) -> None:
        """Test case for get_full_price_items_by_pricelist_id

        List detailed items
        """
        pass

    def test_get_price_list(self) -> None:
        """Test case for get_price_list

        Get specific list
        """
        pass

    def test_get_price_list_by_code(self) -> None:
        """Test case for get_price_list_by_code

        Get list by code
        """
        pass

    def test_get_price_list_items(self) -> None:
        """Test case for get_price_list_items

        Get items in list
        """
        pass

    def test_get_prices_items(self) -> None:
        """Test case for get_prices_items

        Get detailed items
        """
        pass

    def test_list_full_price_items_by_pricelist_id(self) -> None:
        """Test case for list_full_price_items_by_pricelist_id

        List detailed price items for a specific price list
        """
        pass

    def test_list_price_lists(self) -> None:
        """Test case for list_price_lists

        List all price lists
        """
        pass

    def test_price_list_get_price_items_by_price_list_item_ids(self) -> None:
        """Test case for price_list_get_price_items_by_price_list_item_ids

        """
        pass

    def test_set_price_list_items(self) -> None:
        """Test case for set_price_list_items

        Set items in list
        """
        pass

    def test_update_price_list(self) -> None:
        """Test case for update_price_list

        Update list
        """
        pass


if __name__ == '__main__':
    unittest.main()
