# coding: utf-8

"""
    PriceList Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pricelist.models.pricelist_get_price_list_request import PricelistGetPriceListRequest

class TestPricelistGetPriceListRequest(unittest.TestCase):
    """PricelistGetPriceListRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PricelistGetPriceListRequest:
        """Test PricelistGetPriceListRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PricelistGetPriceListRequest`
        """
        model = PricelistGetPriceListRequest()
        if include_optional:
            return PricelistGetPriceListRequest(
                tenant_id = '',
                id = ''
            )
        else:
            return PricelistGetPriceListRequest(
        )
        """

    def testPricelistGetPriceListRequest(self):
        """Test PricelistGetPriceListRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
