# coding: utf-8

"""
    PriceList Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pricelist.models.pricelist_update_price_list_request import PricelistUpdatePriceListRequest

class TestPricelistUpdatePriceListRequest(unittest.TestCase):
    """PricelistUpdatePriceListRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PricelistUpdatePriceListRequest:
        """Test PricelistUpdatePriceListRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PricelistUpdatePriceListRequest`
        """
        model = PricelistUpdatePriceListRequest()
        if include_optional:
            return PricelistUpdatePriceListRequest(
                tenant_id = '',
                id = '',
                payload = pricelist.models.pricelist_update_price_list_request_payload.pricelistUpdatePriceListRequestPayload(
                    is_active = True, 
                    is_default = True, 
                    currency = 'XXX', 
                    vat_included = True, 
                    delivered_duty_paid = True, 
                    segments = [
                        ''
                        ], 
                    markets = [
                        ''
                        ], 
                    channels = [
                        ''
                        ], 
                    type = 'UNKNOWN', 
                    is_system = True, 
                    name = '', 
                    description = '', ),
                payload_mask = ''
            )
        else:
            return PricelistUpdatePriceListRequest(
        )
        """

    def testPricelistUpdatePriceListRequest(self):
        """Test PricelistUpdatePriceListRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
