# coding: utf-8

"""
    PriceList Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pricelist.models.pricelist_get_prices_request import PricelistGetPricesRequest

class TestPricelistGetPricesRequest(unittest.TestCase):
    """PricelistGetPricesRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PricelistGetPricesRequest:
        """Test PricelistGetPricesRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PricelistGetPricesRequest`
        """
        model = PricelistGetPricesRequest()
        if include_optional:
            return PricelistGetPricesRequest(
                tenant_id = '',
                items_grn = [
                    ''
                    ],
                context = pricelist.models.pricelist_price_context.pricelistPriceContext(
                    currency = 'XXX', 
                    segment = '', 
                    segments = [
                        ''
                        ], 
                    market = '', 
                    channel = '', )
            )
        else:
            return PricelistGetPricesRequest(
        )
        """

    def testPricelistGetPricesRequest(self):
        """Test PricelistGetPricesRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
