# coding: utf-8

"""
    PriceList Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pricelist.models.pricelist_get_full_price_items_response import PricelistGetFullPriceItemsResponse

class TestPricelistGetFullPriceItemsResponse(unittest.TestCase):
    """PricelistGetFullPriceItemsResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PricelistGetFullPriceItemsResponse:
        """Test PricelistGetFullPriceItemsResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PricelistGetFullPriceItemsResponse`
        """
        model = PricelistGetFullPriceItemsResponse()
        if include_optional:
            return PricelistGetFullPriceItemsResponse(
                price_items = [
                    pricelist.models.pricelist_get_full_price_item.pricelistGetFullPriceItem(
                        id = '', 
                        grn = '', 
                        item_grn = '', 
                        base_price = pricelist.models.pricelist_money.pricelistMoney(
                            units = '', 
                            micros = 56, ), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        currency = 'XXX', 
                        prices = [
                            pricelist.models.pricelist_get_full_price_item_price.pricelistGetFullPriceItemPrice(
                                price = pricelist.models.pricelist_money.pricelistMoney(
                                    units = '', 
                                    micros = 56, ), 
                                is_enabled = True, 
                                start_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                end_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                order = 56, )
                            ], 
                        has_tier_prices = True, )
                    ]
            )
        else:
            return PricelistGetFullPriceItemsResponse(
        )
        """

    def testPricelistGetFullPriceItemsResponse(self):
        """Test PricelistGetFullPriceItemsResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
