# coding: utf-8

"""
    PriceList Service

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v1
    Contact: info@gemini-commerce.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from pricelist.models.pricelist_currency import PricelistCurrency

class TestPricelistCurrency(unittest.TestCase):
    """PricelistCurrency unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPricelistCurrency(self):
        """Test PricelistCurrency"""
        # inst = PricelistCurrency()

if __name__ == '__main__':
    unittest.main()
